---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thitd-app-gnex
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ycetin94/lesson-158.git
    targetRevision: HEAD
    path: environments/staging/third-app
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true